<a href="https://colab.research.google.com/github/vaishnavi-sreeji/Machine-Learning/blob/main/KNN_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification,make_regression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,r2_score,mean_squared_error,mean_absolute_error
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
X,y=make_classification(n_samples=100,
                        n_features=3,
                        n_classes=2,
                        n_redundant=1,
                        random_state=999)

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [10]:
model=KNeighborsClassifier(n_neighbors=5,algorithm='auto')
model.fit(X_train,y_train)

KNeighborsClassifier()

In [12]:
y_predict=model.predict(X_test)
y_predict

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0])

In [15]:
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92        13
           1       0.94      0.94      0.94        17

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

0.9333333333333333
[[12  1]
 [ 1 16]]


KNN Regrssion

In [19]:
X,y=make_regression(n_samples=100,
                        n_features=2,
                        noise=10,
                        random_state=42)

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [23]:
model=KNeighborsRegressor(n_neighbors=5,algorithm='auto')
model.fit(X_train,y_train)

KNeighborsRegressor()

In [24]:
y_predict=model.predict(X_test)
y_predict

array([ -67.74037609,    8.39607064,  111.30248587,  -11.96862755,
         57.44570321,   57.44570321,  157.88725821,  -99.18633223,
       -167.26881201,  -67.74037609,   72.98689299,  -99.18633223,
        122.45554151,  -42.29305363,  111.51324727,   41.09166427,
        -25.90050219,  -14.16633983,  -83.50401182,   17.79585021,
        -88.94508254,   16.33962164,  -29.15568694,  -68.94011088,
        -97.76669598, -145.03693852,  -96.44144495,   27.3814964 ,
        135.45372158,  131.50421762])

In [26]:
print(r2_score(y_test,y_predict))
print(mean_squared_error(y_test,y_predict))
print(mean_absolute_error(y_test,y_predict))

0.935533064863636
657.1160130042604
20.055758314810685
