<a href="https://colab.research.google.com/github/vaishnavi-sreeji/Machine-Learning/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report




In [3]:
X,y=make_classification(n_samples=1000,
                        n_features=10,

                        n_classes=2,
                        random_state=90
                       )

In [4]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.932317 -1.265163 -1.362227 -0.831033  0.526745 -0.371552 -0.901366   
1   -0.097729  1.013341 -0.119443 -0.508118 -0.998860 -0.166748  0.442596   
2   -0.258327 -1.731124  1.410545 -2.142258  0.671746  0.747660 -0.354159   
3   -0.744067 -1.298020  1.241198  1.882946 -0.746141  0.631014 -0.719521   
4    0.497760  0.815200  0.793029  0.555341  0.202537  0.206912  0.491113   
..        ...       ...       ...       ...       ...       ...       ...   
995  2.470419  1.947759 -2.743203  0.948737  0.255562 -1.284706 -0.417625   
996 -0.293963 -0.593335 -0.418529  1.591476  0.083922 -0.089735  1.298167   
997  0.153540  0.120916  0.685372 -0.528569 -0.974108  0.248471 -1.031343   
998  0.014040 -0.213858  1.063476 -0.001914 -0.678672  0.433459 -1.194330   
999 -1.038552 -1.560003  0.278275  0.209942 -0.671405  0.292912 -0.764702   

            7         8         9  
0   -0.068345  1.250162 -0.628784  
1   -0.303246 -0.553621  0.723407  
2    1.135018  0.499555 -0.406441  
3   -0.117881  0.306688 -1.559776  
4    0.295457 -0.774203 -1.980358  
..        ...       ...       ...  
995 -0.237339 -0.134481  0.419466  
996 -2.629523  0.504814 -0.996673  
997 -1.054770 -0.324811 -0.438889  
998  0.523608 -0.267158 -1.034952  
999  0.622427  0.817368 -1.129908  

[1000 rows x 10 columns]

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=90)

In [7]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [8]:
y_predict=model.predict(X_test)
y_predict

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [9]:
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.9533333333333334
[[131  13]
 [  1 155]]
              precision    recall  f1-score   support

           0       0.99      0.91      0.95       144
           1       0.92      0.99      0.96       156

    accuracy                           0.95       300
   macro avg       0.96      0.95      0.95       300
weighted avg       0.96      0.95      0.95       300



HyperParameter Tuning  **Grid Search Cv**

In [21]:
penality=['l1','l2','elasticnet']
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
c_values=[100,10,0.1,0.01]

params=dict(penalty=penality,solver=solver,C=c_values)

In [14]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [22]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,cv=cv,param_grid=params,scoring="accuracy",n_jobs=2)
grid.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
160 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1169, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=2,
             param_grid={'C': [100, 10, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [23]:
grid.best_params_

{'C': 100, 'penalty': 'l1', 'solver': 'liblinear'}

In [25]:
grid.best_score_

0.9542857142857143

In [ ]:
y_predict=grid.predict(X_test)

In [26]:
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.9533333333333334
[[131  13]
 [  1 155]]
              precision    recall  f1-score   support

           0       0.99      0.91      0.95       144
           1       0.92      0.99      0.96       156

    accuracy                           0.95       300
   macro avg       0.96      0.95      0.95       300
weighted avg       0.96      0.95      0.95       300



**RandomizedSearchCv**

In [28]:
from sklearn.model_selection import RandomizedSearchCV
random=RandomizedSearchCV(estimator=model,cv=5,param_distributions=params,scoring="accuracy",n_jobs=2)
random.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1169, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=2,
                   param_distributions={'C': [100, 10, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [29]:
random.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 10}

In [32]:
random.best_score_

0.9542857142857143

In [33]:
y_predict=random.predict(X_test)

In [34]:
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.95
[[131  13]
 [  2 154]]
              precision    recall  f1-score   support

           0       0.98      0.91      0.95       144
           1       0.92      0.99      0.95       156

    accuracy                           0.95       300
   macro avg       0.95      0.95      0.95       300
weighted avg       0.95      0.95      0.95       300



**LOGISTIC REGRESSION USING OVR(MULTICLASS)**

In [35]:
X,y=make_classification(n_samples=1000,
                        n_features=10,
                        n_informative=3,
                        n_classes=3,
                        random_state=15
                       )

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=15)

In [36]:
model=LogisticRegression(multi_class="ovr")
model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [37]:
y_predict=model.predict(X_test)
y_predict

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [38]:
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.9533333333333334
[[131  13]
 [  1 155]]
              precision    recall  f1-score   support

           0       0.99      0.91      0.95       144
           1       0.92      0.99      0.96       156

    accuracy                           0.95       300
   macro avg       0.96      0.95      0.95       300
weighted avg       0.96      0.95      0.95       300

